# Generated by Django 4.2.6 on 2023-11-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0002_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='alignment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
