# Generated by Django 4.2.6 on 2023-11-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0003_menu_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/image')),
            ],
        ),
    ]
