# Generated by Django 4.2.6 on 2023-11-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_answer_image_alter_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_text', models.CharField(max_length=250)),
                ('slider_content', models.TextField()),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='uploads/image')),
                ('slider_button_text', models.CharField(max_length=250)),
                ('slider_button_file', models.FileField(blank=True, null=True, upload_to='uploads/mycv')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionTopic',
        ),
    ]
