# Generated by Django 4.2.6 on 2023-11-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mainpage_remove_question_topic_remove_question_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='mainpage',
            name='slider_item',
            field=models.ManyToManyField(to='main.skill'),
        ),
    ]
