# Generated by Django 4.2.6 on 2023-11-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_skill_mainpage_slider_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='contact_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='contact_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='skill_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='skill_text',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
